const fs=require('fs'),vm=require('vm'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'../src/index.html'),'utf8');
const css=fs.readFileSync(path.join(__dirname,'../src/style.css'),'utf8');
const runtimeFiles=['../src/levels.js','../src/runtime/core.js','../src/runtime/audio.js','../src/runtime/physics.js','../src/runtime/render-world.js','../src/runtime/render-entities.js','../src/runtime/render-hud.js','../src/runtime/ui.js'];
let js=runtimeFiles.map(f=>fs.readFileSync(path.join(__dirname,f),'utf8')).join('\n');
const assert=(c,m)=>{if(!c)throw Error(m)};
assert(/id="time"/.test(html)&&/id="next"/.test(html),'live HUD must contain timer and objective');
assert(!/id="level"|id="shots"|id="stars"|id="score"/.test(html),'live HUD still contains nonessential stats');
assert(/padding:6px 12px/.test(css)&&/border-radius:18px/.test(css),'compact HUD styling regressed');
assert(/F===1&&Y<210/.test(js),'level intro is not time-limited');
assert(/roundRect\(250,510,460,64,24\)/.test(js),'level intro is not bottom-centered');
assert(/#fffdf8f7/.test(js),'level intro background is not sufficiently opaque');
assert(/bold 18px sans-serif/.test(js)&&/bold 11px sans-serif/.test(js),'level intro typography is not prominent enough');
assert(/TOTAL '\+\$n\+'★ · SCORE/.test(js),'pause menu is missing cumulative stats');
assert(/U\.h\.style\.display=F===1\|\|F===7/.test(js),'live HUD is not hidden outside gameplay');
js=js.replace('$2();$0();_b()',`globalThis.HUDTEST={draw:$8,set:(f,y,i,l=0)=>{F=f;Y=y;L=l;B=i==null?null:{i};$0()},frame:_a};$2();$0();_b()`);
const noop=()=>{},grad=()=>({addColorStop:noop});let cards=0;
const ctx={beginPath:noop,arc:noop,fill:noop,stroke:noop,fillRect:noop,strokeRect:noop,moveTo:noop,lineTo:noop,quadraticCurveTo:noop,save:noop,restore:noop,translate:noop,rotate:noop,scale:noop,setTransform:noop,clearRect:noop,setLineDash:noop,fillText:noop,createRadialGradient:grad,createLinearGradient:grad,roundRect(){cards++}};
const canvas={getContext:()=>ctx,getBoundingClientRect:()=>({width:960,height:600,left:0,top:0}),addEventListener:noop};
const els={};const document={querySelector:s=>s==='#c'?canvas:(els[s]??={textContent:'',style:{}})};
const sandbox={console,document,localStorage:{},innerWidth:960,innerHeight:600,devicePixelRatio:1,addEventListener:noop,requestAnimationFrame:noop,setTimeout:()=>1,Math,atob:s=>Buffer.from(s,'base64').toString('binary'),window:{AudioContext:function(){}}};
vm.createContext(sandbox);vm.runInContext(js,sandbox,{timeout:1000});
sandbox.HUDTEST.set(1,0,null);cards=0;sandbox.HUDTEST.draw();assert(cards===1,'level intro should draw exactly one card at level start');
sandbox.HUDTEST.set(1,211,null);cards=0;sandbox.HUDTEST.draw();assert(cards===0,'level intro should disappear after ~3.5 seconds');
sandbox.HUDTEST.set(1,20,0,20);assert(/^NEXT 1\/2/.test(els['#next'].textContent),'objective did not initialize to first cloud');
sandbox.HUDTEST.set(1,20,1,20);assert(/^NEXT 2\/2/.test(els['#next'].textContent),'objective did not follow cloud progress');
sandbox.HUDTEST.set(4,20,null,20);sandbox.HUDTEST.frame();assert(els['#hud'].style.display==='none','HUD should hide on pause');
sandbox.HUDTEST.set(1,20,null,20);sandbox.HUDTEST.frame();assert(els['#hud'].style.display==='flex','HUD should return during play');
console.log(JSON.stringify({status:'PASS',objective:els['#next'].textContent,liveHUD:'timer+objective only',intro:'bottom+opaque+large'}));
