const fs=require('fs'),vm=require('vm'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'../src/index.html'),'utf8');
const css=fs.readFileSync(path.join(__dirname,'../src/style.css'),'utf8');
const runtimeFiles=['../src/levels.js','../src/runtime/core.js','../src/runtime/audio.js','../src/runtime/physics.js','../src/runtime/render-world.js','../src/runtime/render-entities.js','../src/runtime/render-hud.js','../src/runtime/ui.js'];
let js=runtimeFiles.map(f=>fs.readFileSync(path.join(__dirname,f),'utf8')).join('\n');
const assert=(c,m)=>{if(!c)throw Error(m)};
assert(/id="time"/.test(html)&&!/id="next"/.test(html),'live HUD should contain only the timer');
assert(!/id="level"|id="shots"|id="stars"|id="score"/.test(html),'live HUD still contains nonessential stats');
assert(/padding:6px 12px/.test(css)&&/border-radius:18px/.test(css)&&!/#next/.test(css),'timer-only HUD styling regressed');
assert(/F===1&&Y<210/.test(js),'level intro is not time-limited');
assert(/let y=mo\?105:510/.test(js)&&/roundRect\(250,y,460,64,24\)/.test(js),'level intro must move above mobile controls');
assert(/#fffdf8f7/.test(js),'level intro background is not sufficiently opaque');
assert(/bold 18px sans-serif/.test(js)&&/bold 11px sans-serif/.test(js),'level intro typography is not prominent enough');
assert(/fillText\(ml\(l\),W\/2,y\+48\)/.test(js),'level intro should expose the active mechanic vocabulary');
assert(!/AIM HORN · CLICK · CHEER THE CLOUDS/.test(js),'generic intro tagline survived mechanic-readout redesign');
assert(/TOTAL '\+\$n\+'★ · SCORE/.test(js),'pause menu is missing cumulative stats');
assert(/WHITE RING = CURRENT CLOUD/.test(js)&&/3 ABOVE = EXACT BOUNCES/.test(js),'first-menu rules legend missing');
assert(/roundRect\(270,448,420,96,20\)/.test(js),'first-menu rules legend should sit at the bottom');
assert(/createLinearGradient\(270,0,690,0\)/.test(js),'first-menu rules legend should use a dark rainbow gradient');
assert(/U\.h\.style\.display=F===1\|\|F===7/.test(js),'live HUD is not hidden outside gameplay');
js=js.replace('$2();$0();_b()',`globalThis.HUDTEST={draw:$8,set:(f,y,i,l=0,m=0)=>{F=f;Y=y;L=l;mo=m;B=i==null?null:{i};$0()},frame:_a};$2();$0();_b()`);
const noop=()=>{},grad=()=>({addColorStop:noop});let cards=0,ys=[];
const ctx={beginPath:noop,arc:noop,fill:noop,stroke:noop,fillRect:noop,strokeRect:noop,moveTo:noop,lineTo:noop,quadraticCurveTo:noop,save:noop,restore:noop,translate:noop,rotate:noop,scale:noop,setTransform:noop,clearRect:noop,setLineDash:noop,fillText:noop,createRadialGradient:grad,createLinearGradient:grad,roundRect(x,y){cards++;ys.push(y)}};
const canvas={getContext:()=>ctx,getBoundingClientRect:()=>({width:960,height:600,left:0,top:0}),addEventListener:noop};
const els={};const document={querySelector:s=>s==='#c'?canvas:(els[s]??={textContent:'',style:{}})};
const sandbox={console,document,localStorage:{},innerWidth:960,innerHeight:600,devicePixelRatio:1,addEventListener:noop,requestAnimationFrame:noop,setTimeout:()=>1,Math,atob:s=>Buffer.from(s,'base64').toString('binary'),window:{AudioContext:function(){}}};
vm.createContext(sandbox);vm.runInContext(js,sandbox,{timeout:1000});
sandbox.HUDTEST.set(1,0,null);cards=0;ys=[];sandbox.HUDTEST.draw();assert(cards===1&&ys[0]===510,'desktop intro should remain bottom-centered');
sandbox.HUDTEST.set(1,0,null,0,1);cards=0;ys=[];sandbox.HUDTEST.draw();assert(ys.includes(105),'mobile intro should move above the control deck');
sandbox.HUDTEST.set(1,211,null);cards=0;sandbox.HUDTEST.draw();assert(cards===0,'level intro should disappear after ~3.5 seconds');
sandbox.HUDTEST.set(4,20,null,20);sandbox.HUDTEST.frame();assert(els['#hud'].style.display==='none','HUD should hide on pause');
sandbox.HUDTEST.set(1,20,null,20);sandbox.HUDTEST.frame();assert(els['#hud'].style.display==='flex','HUD should return during play');
console.log(JSON.stringify({status:'PASS',liveHUD:'timer only',mobileIntroY:105}));
