const fs=require('fs'),path=require('path');
const hud=fs.readFileSync(path.join(__dirname,'../src/runtime/render-hud.js'),'utf8');
const ui=fs.readFileSync(path.join(__dirname,'../src/runtime/ui.js'),'utf8');
const assert=(c,m)=>{if(!c)throw Error(m)};
assert(/function \$T\(\)/.test(hud),'menu rules helper missing');
assert(/WHITE RING = CURRENT CLOUD/.test(hud),'active-cloud rule missing');
assert(/2 IN CLOUD = HIT SECOND/.test(hud),'cloud-order rule missing');
assert(/3 ABOVE = EXACT BOUNCES/.test(hud),'bounce-count rule missing');
assert(/BOUNCE = WALL \/ PRISM RICOCHET/.test(hud),'bounce definition missing');
assert(/K\(x,y-r-10,9,'#24162f'\);X\.fillStyle='#fff';X\.fillText\('3'/.test(hud),'bounce example must use dark badge + white number');
assert(/\$T\(\);_g\(365,315,230,42,'PLAY/.test(hud),'rules legend is not integrated with centered play controls');
assert(/\[365,315,230,42\]/.test(ui)&&/\[365,370,230,42\]/.test(ui),'menu hit boxes do not match centered buttons');
assert(/roundRect\(270,448,420,96,20\)/.test(hud),'rules card should sit at the bottom');
assert(/createLinearGradient\(270,0,690,0\)/.test(hud)&&/#34183f/.test(hud)&&/#12394d/.test(hud),'rules card lost dark rainbow treatment');
assert(/fillText\('TOUCH: TAP OR DRAG \+ RELEASE · MOUSE: AIM \+ CLICK',W\/2,575\)/.test(hud),'mobile-aware control legend should remain below the rules card');
assert(/SOUND '\+\(\$y\?'ON':'OFF'\)/.test(hud)&&/PATH '\+\(\$a\?'ON':'OFF'\)/.test(hud),'pause menu must expose touch-accessible sound/path toggles');
console.log(JSON.stringify({status:'PASS',rules:'ring=current, cloud number=order, dark badge=bounces',layout:'dark bottom card + centered buttons + mobile-aware controls'}));
