const fs=require('fs'),path=require('path');
const hud=fs.readFileSync(path.join(__dirname,'../src/runtime/render-hud.js'),'utf8');
const ui=fs.readFileSync(path.join(__dirname,'../src/runtime/ui.js'),'utf8');
const assert=(c,m)=>{if(!c)throw Error(m)};
assert(/function \$T\(\)/.test(hud),'menu rules helper missing');
assert(/WHITE RING = CURRENT CLOUD/.test(hud),'active-cloud rule missing');
assert(/2 IN CLOUD = HIT SECOND/.test(hud),'cloud-order rule missing');
assert(/3 ABOVE = EXACT BOUNCES/.test(hud),'bounce-count rule missing');
assert(/BOUNCE = WALL \/ PRISM RICOCHET/.test(hud),'bounce definition missing');
assert(/RING = CURRENT · NUMBER = ORDER · BADGE = EXACT RICOCHETS/.test(hud),'first demo must restate target grammar');
assert(/K\(x,y-r-10,9,'#24162f'\);X\.fillStyle='#fff';X\.fillText\('3'/.test(hud),'bounce example must use dark badge + white number');
assert(/\$T\(\);_g\(365,315,230,42,'PLAY/.test(hud),'rules legend is not integrated with centered play controls');
assert(/\[365,315,230,42\]/.test(ui)&&/\[365,370,230,42\]/.test(ui),'menu hit boxes do not match centered buttons');
assert(/roundRect\(270,448,420,96,20\)/.test(hud),'rules card should sit at the bottom');
assert(/createLinearGradient\(270,0,690,0\)/.test(hud)&&/#34183f/.test(hud)&&/#12394d/.test(hud),'rules card lost dark rainbow treatment');
assert(/MOBILE: AIM WHEEL \+ FIRE/.test(hud),'mobile control legend missing');
assert(/DESKTOP: KEYS \+ SPACE \/ MOUSE \+ CLICK/.test(hud),'desktop dual-mode control legend missing');
assert(/_g\(390,420,180,28,'AIM '\+\(cm\?'MOUSE':'KEYS'\)\)/.test(hud),'main-menu AIM mode toggle missing');
assert(/SOUND '\+\(\$y\?'ON':'OFF'\)/.test(hud)&&/PATH '\+\(\$a\?'ON':'OFF'\)/.test(hud)&&/AIM '\+\(cm\?'MOUSE':'KEYS'\)/.test(hud),'pause menu must expose sound/path/aim toggles');
console.log(JSON.stringify({status:'PASS',rules:'ring=current, number=order, badge=ricochets',mobile:'aim wheel + fire',desktop:'keyboard default + mouse toggle'}));
